version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Services/notificationsvc
hooks:
  BeforeInstall:
    - location: ops-script/before-install
      timeout: 120
      runas: root
  AfterInstall:
    - location: ops-script/after-install
      timeout: 300
      runas: root
