version: '3.7'

networks:
  dcanetwork:
    name: dcanetwork
    driver: bridge

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  pgadmin-data:

services:

  dcadb:
    image: postgres:15
    container_name: dcadb
    restart: always
    networks:
      - dcanetwork
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  dcapgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - dcanetwork
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - dcadb

  dcaredis:
    image: redis:latest
    container_name: dcaredis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    env_file:
      - ./.env.redis
    command: redis-server --save 20 1 --loglevel warning --requirepass yKVge8oLd2t81
    volumes:
      - ./redisdata:/var/lib/redisdata
    networks:
      - dcanetwork
    restart: always

  dcakeycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: dcakeycloak
    networks:
      - dcanetwork
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=abx@xya.com
      - KEYCLOAK_ADMIN_PASSWORD=Password1!
      - KC_PROXY=edge
      - KC_DB_URL=jdbc:postgresql://dcadb:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    depends_on:
      - dcadb
    restart: always

  dcaPwaApp:
    image: <account_id>.dkr.ecr.us-east-2.amazonaws.com/PwaApp:01
    container_name: PwaApp
    env_file:
      - ./.env.PwaApp
    networks:
      - dcanetwork
    ports:
      - 8000:8000
    environment:
      - APP_TYPE=service
    depends_on:
      - "dcadb"
      - "dcaredis"
      - "dcakeycloak"
